# SPDX-FileCopyrightText: Elio Severo Junior <elioseverojunior@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1

[[gitignore.section]]

[[gitignore.section.rule]]
note = """
SPDX-FileCopyrightText: Elio Severo Junior <elioseverojunior@gmail.com>

SPDX-License-Identifier: MIT OR Apache-2.0"""

[[gitignore.section]]
level = 3
name = "Rust"
note = "Cargo Ignores"

[[gitignore.section.rule]]
ignore = ["/target"]

[[gitignore.section.rule]]
ignore = ["**/dist"]
note = "Cargo Package"

[[gitignore.section.rule]]
ignore = ["**/.cargo-vet"]
note = "Cargo Vet"
